# ================================
# WAR MACHINE — MASTER CONFIG
# GOD MODE PRO STABLE BUILD
# ================================

# ===== SCANNER SETTINGS =====
SCAN_INTERVAL = 60
UNIVERSE_LIMIT = 1000

# ===== MARKET FILTERS =====
MIN_MARKET_CAP = 2_000_000_000
MIN_PRICE = 2
MAX_PRICE = 500

# ===== MOMENTUM FILTERS =====
MIN_RELATIVE_VOLUME = 1.5
MIN_PERCENT_MOVE = 1.0

# ===== CONFIRMATION ENGINE =====
CONFIRM_CLOSE_ABOVE_RATIO = 0.6
CONFIRM_CANDLE_BODY_MIN = 0.4
CONFIRM_VOLUME_SPIKE = 1.2

# ===== RETEST ENGINE =====
RETEST_TOLERANCE = 0.003
MAX_RETEST_WAIT_MIN = 30

# ===== RISK MODEL =====
RISK_REWARD_RATIO = 2.0

STOP_BUFFER = 0.002
STOP_BUFFER_DOLLARS = 0.15

MIN_RISK_PX = 0.20   # prevents ultra tight stops

TARGET1_RR = 2.0
TARGET2_RR = 3.0

# ===== DISCORD =====
SEND_SETUP_ALERTS = True
SEND_CONFIRM_ALERTS = True
SEND_RESULT_ALERTS = True

# ===== GOD MODE =====
GOD_MODE = True
SNIPER_MODE = True
LEARNING_MODE = True
