[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "postgresql", "stdenv.cc.cc.lib"]

[phases.install]
cmds = ["pip install -r requirements.txt --break-system-packages"]

[start]
cmd = "python -m app.core.scanner"

[variables]
NIXPACKS_PATH = ""
