$ErrorActionPreference = 'Stop'
Write-Host 'Rolling back migration...' -ForegroundColor Yellow
if (Test-Path 'results/backtests/backtest_results.json') { Move-Item 'results/backtests/backtest_results.json' 'backtest_results.json' -Force; Write-Host '   Restored: backtest_results.json' -ForegroundColor Green }
if (Test-Path 'results/backtests/quick_backtest_results.csv') { Move-Item 'results/backtests/quick_backtest_results.csv' 'quick_backtest_results.csv' -Force; Write-Host '   Restored: quick_backtest_results.csv' -ForegroundColor Green }
if (Test-Path 'results/optimization/optimization_results.json') { Move-Item 'results/optimization/optimization_results.json' 'optimization_results.json' -Force; Write-Host '   Restored: optimization_results.json' -ForegroundColor Green }
if (Test-Path 'results/optimization/optimized_filter_parameters.json') { Move-Item 'results/optimization/optimized_filter_parameters.json' 'optimized_filter_parameters.json' -Force; Write-Host '   Restored: optimized_filter_parameters.json' -ForegroundColor Green }
if (Test-Path 'results/optimization/effective_filters_exhaustive.json') { Move-Item 'results/optimization/effective_filters_exhaustive.json' 'effective_filters_exhaustive.json' -Force; Write-Host '   Restored: effective_filters_exhaustive.json' -ForegroundColor Green }
if (Test-Path 'results/optimization/two_phase_optimization_results.json') { Move-Item 'results/optimization/two_phase_optimization_results.json' 'two_phase_optimization_results.json' -Force; Write-Host '   Restored: two_phase_optimization_results.json' -ForegroundColor Green }
if (Test-Path 'results/optimization/war_machine_optimized.json') { Move-Item 'results/optimization/war_machine_optimized.json' 'war_machine_optimized.json' -Force; Write-Host '   Restored: war_machine_optimized.json' -ForegroundColor Green }
if (Test-Path 'results/indicators/indicator_backtest_detailed.json') { Move-Item 'results/indicators/indicator_backtest_detailed.json' 'indicator_backtest_detailed.json' -Force; Write-Host '   Restored: indicator_backtest_detailed.json' -ForegroundColor Green }
if (Test-Path 'results/indicators/indicator_backtest_results.csv') { Move-Item 'results/indicators/indicator_backtest_results.csv' 'indicator_backtest_results.csv' -Force; Write-Host '   Restored: indicator_backtest_results.csv' -ForegroundColor Green }
if (Test-Path 'results/indicators/indicator_backtest_results.json') { Move-Item 'results/indicators/indicator_backtest_results.json' 'indicator_backtest_results.json' -Force; Write-Host '   Restored: indicator_backtest_results.json' -ForegroundColor Green }
if (Test-Path 'results/indicators/indicator_backtest_results_REAL.csv') { Move-Item 'results/indicators/indicator_backtest_results_REAL.csv' 'indicator_backtest_results_REAL.csv' -Force; Write-Host '   Restored: indicator_backtest_results_REAL.csv' -ForegroundColor Green }
if (Test-Path 'results/indicators/indicator_backtest_results_REAL.json') { Move-Item 'results/indicators/indicator_backtest_results_REAL.json' 'indicator_backtest_results_REAL.json' -Force; Write-Host '   Restored: indicator_backtest_results_REAL.json' -ForegroundColor Green }
if (Test-Path 'results/indicators/indicator_backtest_summary.csv') { Move-Item 'results/indicators/indicator_backtest_summary.csv' 'indicator_backtest_summary.csv' -Force; Write-Host '   Restored: indicator_backtest_summary.csv' -ForegroundColor Green }
if (Test-Path 'results/indicators/quick_indicator_results.csv') { Move-Item 'results/indicators/quick_indicator_results.csv' 'quick_indicator_results.csv' -Force; Write-Host '   Restored: quick_indicator_results.csv' -ForegroundColor Green }
if (Test-Path 'results/validation/validation_signals.csv') { Move-Item 'results/validation/validation_signals.csv' 'validation_signals.csv' -Force; Write-Host '   Restored: validation_signals.csv' -ForegroundColor Green }
if (Test-Path 'scripts/backtesting/backtest_optimized_params.py') { Move-Item 'scripts/backtesting/backtest_optimized_params.py' 'backtest_optimized_params.py' -Force; Write-Host '   Restored: backtest_optimized_params.py' -ForegroundColor Green }
if (Test-Path 'scripts/backtesting/production_indicator_backtest.py') { Move-Item 'scripts/backtesting/production_indicator_backtest.py' 'production_indicator_backtest.py' -Force; Write-Host '   Restored: production_indicator_backtest.py' -ForegroundColor Green }
if (Test-Path 'scripts/optimization/smart_optimization.py') { Move-Item 'scripts/optimization/smart_optimization.py' 'smart_optimization.py' -Force; Write-Host '   Restored: smart_optimization.py' -ForegroundColor Green }
if (Test-Path 'scripts/analysis/analyze_ml_training_data.py') { Move-Item 'scripts/analysis/analyze_ml_training_data.py' 'analyze_ml_training_data.py' -Force; Write-Host '   Restored: analyze_ml_training_data.py' -ForegroundColor Green }
if (Test-Path 'scripts/analysis/inspect_signal_outcomes.py') { Move-Item 'scripts/analysis/inspect_signal_outcomes.py' 'inspect_signal_outcomes.py' -Force; Write-Host '   Restored: inspect_signal_outcomes.py' -ForegroundColor Green }
if (Test-Path 'scripts/analysis/target_discovery.py') { Move-Item 'scripts/analysis/target_discovery.py' 'target_discovery.py' -Force; Write-Host '   Restored: target_discovery.py' -ForegroundColor Green }
if (Test-Path 'scripts/database/check_database.py') { Move-Item 'scripts/database/check_database.py' 'check_database.py' -Force; Write-Host '   Restored: check_database.py' -ForegroundColor Green }
if (Test-Path 'scripts/database/inspect_database_schema.py') { Move-Item 'scripts/database/inspect_database_schema.py' 'inspect_database_schema.py' -Force; Write-Host '   Restored: inspect_database_schema.py' -ForegroundColor Green }
if (Test-Path 'scripts/database/setup_database.py') { Move-Item 'scripts/database/setup_database.py' 'setup_database.py' -Force; Write-Host '   Restored: setup_database.py' -ForegroundColor Green }
if (Test-Path 'scripts/database/load_historical_data.py') { Move-Item 'scripts/database/load_historical_data.py' 'load_historical_data.py' -Force; Write-Host '   Restored: load_historical_data.py' -ForegroundColor Green }
if (Test-Path 'scripts/maintenance/update_sniper_greeks.py') { Move-Item 'scripts/maintenance/update_sniper_greeks.py' 'update_sniper_greeks.py' -Force; Write-Host '   Restored: update_sniper_greeks.py' -ForegroundColor Green }
if (Test-Path 'scripts/maintenance/production_helpers.py') { Move-Item 'scripts/maintenance/production_helpers.py' 'production_helpers.py' -Force; Write-Host '   Restored: production_helpers.py' -ForegroundColor Green }
if (Test-Path 'scripts/powershell/dependency_analyzer.ps1') { Move-Item 'scripts/powershell/dependency_analyzer.ps1' 'dependency_analyzer.ps1' -Force; Write-Host '   Restored: dependency_analyzer.ps1' -ForegroundColor Green }
if (Test-Path 'scripts/powershell/restore_and_deploy.ps1') { Move-Item 'scripts/powershell/restore_and_deploy.ps1' 'restore_and_deploy.ps1' -Force; Write-Host '   Restored: restore_and_deploy.ps1' -ForegroundColor Green }
if (Test-Path 'scripts/config/super_indicator_config.py') { Move-Item 'scripts/config/super_indicator_config.py' 'super_indicator_config.py' -Force; Write-Host '   Restored: super_indicator_config.py' -ForegroundColor Green }
if (Test-Path 'scripts/config/super_indicator_filters.py') { Move-Item 'scripts/config/super_indicator_filters.py' 'super_indicator_filters.py' -Force; Write-Host '   Restored: super_indicator_filters.py' -ForegroundColor Green }
Write-Host 'Rollback complete!' -ForegroundColor Green
