"""
Signal Analytics Module
Tracks all signals generated by the scanner and monitors their outcomes.

Features:
  - Logs every signal with entry, stop, target details
  - Tracks signal outcomes (hit target, hit stop, expired)
  - Calculates win rate, profit factor, average R:R
  - Generates performance reports for tuning
  - Stores in PostgreSQL for historical analysis

Usage:
  from signal_analytics import log_signal, update_signal_outcome, get_performance_stats
  
  # When signal fires
  log_signal(ticker, direction, entry, stop, target, confidence, ...)
  
  # When outcome is known (target hit, stop hit, or time expired)
  update_signal_outcome(signal_id, outcome, exit_price, exit_time)
  
  # Get performance stats
  stats = get_performance_stats(days=30)
"""

from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from typing import Dict, List, Optional
import db_connection
from db_connection import get_conn, ph, dict_cursor, serial_pk

ET = ZoneInfo("America/New_York")


class SignalAnalytics:
    def __init__(self, db_path: str = "market_memory.db"):
        self.db_path = db_path
        self._initialize_tables()

    def _initialize_tables(self):
        """Create signal tracking tables."""
        conn = get_conn(self.db_path)
        cursor = conn.cursor()

        # Main signals table
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS signals (
                id              {serial_pk()},
                ticker          TEXT NOT NULL,
                direction       TEXT NOT NULL,
                signal_time     TIMESTAMP NOT NULL,
                entry_price     REAL NOT NULL,
                stop_price      REAL NOT NULL,
                target_price    REAL NOT NULL,
                risk            REAL NOT NULL,
                reward          REAL NOT NULL,
                risk_reward     REAL NOT NULL,
                confidence      INTEGER NOT NULL,
                volume_multiple REAL,
                atr             REAL,
                signal_type     TEXT,
                
                -- Outcome tracking
                outcome         TEXT,
                exit_price      REAL,
                exit_time       TIMESTAMP,
                pnl             REAL,
                pnl_r           REAL,
                hold_duration   INTEGER,
                
                -- Metadata
                notes           TEXT,
                created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Migration: Add outcome columns if they don't exist (for existing tables)
        if db_connection.USE_POSTGRES:
            try:
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS outcome TEXT")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS exit_price REAL")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS exit_time TIMESTAMP")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS pnl REAL")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS pnl_r REAL")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS hold_duration INTEGER")
                conn.commit()
            except Exception as e:
                # Columns already exist or other error - continue
                conn.rollback()

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_ticker_time
            ON signals(ticker, signal_time DESC)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_outcome
            ON signals(outcome)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_time
            ON signals(signal_time DESC)
        """)

        conn.commit()
        conn.close()
        print("[ANALYTICS] Signal tracking tables initialized")

    def log_signal(self,
                   ticker: str,
                   direction: str,
                   entry: float,
                   stop: float,
                   target: float,
                   confidence: int,
                   volume_multiple: Optional[float] = None,
                   atr: Optional[float] = None,
                   signal_type: Optional[str] = None,
                   notes: Optional[str] = None) -> int:
        """
        Log a new signal to the database.
        Returns the signal ID for later outcome tracking.
        """
        now_et = datetime.now(ET).replace(tzinfo=None)
        risk = abs(entry - stop)
        reward = abs(target - entry)
        risk_reward = reward / risk if risk > 0 else 0

        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)

        if db_connection.USE_POSTGRES:
            sql = f"""
                INSERT INTO signals (
                    ticker, direction, signal_time, entry_price, stop_price,
                    target_price, risk, reward, risk_reward, confidence,
                    volume_multiple, atr, signal_type, notes
                ) VALUES (
                    {p}, {p}, {p}, {p}, {p},
                    {p}, {p}, {p}, {p}, {p},
                    {p}, {p}, {p}, {p}
                ) RETURNING id
            """
        else:
            sql = f"""
                INSERT INTO signals (
                    ticker, direction, signal_time, entry_price, stop_price,
                    target_price, risk, reward, risk_reward, confidence,
                    volume_multiple, atr, signal_type, notes
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """

        cursor.execute(sql, (
            ticker, direction, now_et, entry, stop,
            target, risk, reward, risk_reward, confidence,
            volume_multiple, atr, signal_type, notes
        ))

        if db_connection.USE_POSTGRES:
            signal_id = cursor.fetchone()["id"]
        else:
            signal_id = cursor.lastrowid

        conn.commit()
        conn.close()

        print(f"[ANALYTICS] 📊 Logged signal #{signal_id}: {ticker} {direction} @ ${entry:.2f}")
        return signal_id

    def update_signal_outcome(self,
                            signal_id: int,
                            outcome: str,
                            exit_price: float,
                            exit_time: Optional[datetime] = None) -> None:
        """
        Update signal outcome when target/stop is hit or signal expires.
        
        Args:
            signal_id: ID from log_signal()
            outcome: 'WIN' | 'LOSS' | 'BREAKEVEN' | 'EXPIRED'
            exit_price: Actual exit price
            exit_time: Exit timestamp (defaults to now)
        """
        if exit_time is None:
            exit_time = datetime.now(ET).replace(tzinfo=None)

        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)

        # Get original signal data
        cursor.execute(f"""
            SELECT entry_price, stop_price, target_price, direction, signal_time, risk
            FROM signals WHERE id = {p}
        """, (signal_id,))
        row = cursor.fetchone()
        if not row:
            print(f"[ANALYTICS] ⚠️ Signal #{signal_id} not found")
            conn.close()
            return

        entry = row["entry_price"]
        direction = row["direction"]
        signal_time = row["signal_time"]
        risk = row["risk"]

        # Calculate P&L
        if direction.lower() in ["bull", "long", "buy"]:
            pnl = exit_price - entry
        else:
            pnl = entry - exit_price

        pnl_r = pnl / risk if risk > 0 else 0

        # Calculate hold duration in minutes
        if isinstance(signal_time, str):
            signal_time = datetime.fromisoformat(signal_time)
        hold_duration = int((exit_time - signal_time).total_seconds() / 60)

        # Update record
        cursor.execute(f"""
            UPDATE signals
            SET outcome = {p}, exit_price = {p}, exit_time = {p},
                pnl = {p}, pnl_r = {p}, hold_duration = {p}
            WHERE id = {p}
        """, (outcome, exit_price, exit_time, pnl, pnl_r, hold_duration, signal_id))

        conn.commit()
        conn.close()

        print(f"[ANALYTICS] ✅ Signal #{signal_id} outcome: {outcome} | "
              f"P&L: ${pnl:+.2f} ({pnl_r:+.2f}R) | Hold: {hold_duration}m")

    def get_performance_stats(self, days: int = 30) -> Dict:
        """
        Calculate performance statistics for completed signals.
        
        Returns:
            {
                'total_signals': int,
                'completed': int,
                'wins': int,
                'losses': int,
                'win_rate': float,
                'avg_win': float,
                'avg_loss': float,
                'profit_factor': float,
                'avg_rr': float,
                'avg_hold_mins': float,
                'total_pnl': float,
                'total_r': float,
                'by_ticker': dict,
                'by_direction': dict
            }
        """
        cutoff = datetime.now(ET) - timedelta(days=days)
        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)

        # All signals in period
        cursor.execute(f"""
            SELECT COUNT(*) as cnt FROM signals
            WHERE signal_time >= {p}
        """, (cutoff,))
        total_signals = cursor.fetchone()["cnt"]

        # Completed signals only
        cursor.execute(f"""
            SELECT ticker, direction, outcome, pnl, pnl_r, hold_duration, risk_reward
            FROM signals
            WHERE signal_time >= {p}
              AND outcome IS NOT NULL
        """, (cutoff,))
        rows = cursor.fetchall()
        conn.close()

        if not rows:
            return {
                'total_signals': total_signals,
                'completed': 0,
                'wins': 0,
                'losses': 0,
                'win_rate': 0.0,
                'avg_win': 0.0,
                'avg_loss': 0.0,
                'profit_factor': 0.0,
                'avg_rr': 0.0,
                'avg_hold_mins': 0.0,
                'total_pnl': 0.0,
                'total_r': 0.0,
                'by_ticker': {},
                'by_direction': {}
            }

        completed = len(rows)
        wins = [r for r in rows if r["outcome"] == "WIN"]
        losses = [r for r in rows if r["outcome"] == "LOSS"]

        win_count = len(wins)
        loss_count = len(losses)
        win_rate = (win_count / completed * 100) if completed > 0 else 0.0

        avg_win = sum(r["pnl"] for r in wins) / win_count if win_count > 0 else 0.0
        avg_loss = sum(r["pnl"] for r in losses) / loss_count if loss_count > 0 else 0.0

        total_wins_pnl = sum(r["pnl"] for r in wins)
        total_losses_pnl = abs(sum(r["pnl"] for r in losses))
        profit_factor = (total_wins_pnl / total_losses_pnl) if total_losses_pnl > 0 else 0.0

        avg_rr = sum(r["risk_reward"] for r in rows) / completed if completed > 0 else 0.0
        avg_hold = sum(r["hold_duration"] or 0 for r in rows) / completed if completed > 0 else 0.0

        total_pnl = sum(r["pnl"] or 0 for r in rows)
        total_r = sum(r["pnl_r"] or 0 for r in rows)

        # By ticker
        by_ticker = {}
        for row in rows:
            t = row["ticker"]
            if t not in by_ticker:
                by_ticker[t] = {'wins': 0, 'losses': 0, 'pnl': 0.0}
            if row["outcome"] == "WIN":
                by_ticker[t]['wins'] += 1
            elif row["outcome"] == "LOSS":
                by_ticker[t]['losses'] += 1
            by_ticker[t]['pnl'] += (row["pnl"] or 0)

        # By direction
        by_direction = {}
        for row in rows:
            d = row["direction"]
            if d not in by_direction:
                by_direction[d] = {'wins': 0, 'losses': 0, 'pnl': 0.0}
            if row["outcome"] == "WIN":
                by_direction[d]['wins'] += 1
            elif row["outcome"] == "LOSS":
                by_direction[d]['losses'] += 1
            by_direction[d]['pnl'] += (row["pnl"] or 0)

        return {
            'total_signals': total_signals,
            'completed': completed,
            'wins': win_count,
            'losses': loss_count,
            'win_rate': win_rate,
            'avg_win': avg_win,
            'avg_loss': avg_loss,
            'profit_factor': profit_factor,
            'avg_rr': avg_rr,
            'avg_hold_mins': avg_hold,
            'total_pnl': total_pnl,
            'total_r': total_r,
            'by_ticker': by_ticker,
            'by_direction': by_direction
        }

    def get_recent_signals(self, limit: int = 50) -> List[Dict]:
        """Get most recent signals with outcomes."""
        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)
        cursor.execute(f"""
            SELECT id, ticker, direction, signal_time, entry_price, stop_price,
                   target_price, risk, reward, risk_reward, confidence,
                   outcome, exit_price, exit_time, pnl, pnl_r, hold_duration
            FROM signals
            ORDER BY signal_time DESC
            LIMIT {p}
        """, (limit,))
        rows = cursor.fetchall()
        conn.close()
        return [dict(row) for row in rows]

    def print_performance_report(self, days: int = 30):
        """Print formatted performance report."""
        stats = self.get_performance_stats(days)

        print("\n" + "="*70)
        print(f"SIGNAL PERFORMANCE REPORT - Last {days} Days")
        print("="*70)
        print(f"Total Signals:    {stats['total_signals']}")
        print(f"Completed:        {stats['completed']}")
        print(f"Wins:             {stats['wins']}")
        print(f"Losses:           {stats['losses']}")
        print(f"Win Rate:         {stats['win_rate']:.1f}%")
        print(f"Avg Win:          ${stats['avg_win']:.2f}")
        print(f"Avg Loss:         ${stats['avg_loss']:.2f}")
        print(f"Profit Factor:    {stats['profit_factor']:.2f}")
        print(f"Avg R:R:          {stats['avg_rr']:.2f}")
        print(f"Avg Hold:         {stats['avg_hold_mins']:.0f} mins")
        print(f"Total P&L:        ${stats['total_pnl']:+.2f}")
        print(f"Total R:          {stats['total_r']:+.2f}R")

        if stats['by_ticker']:
            print("\n" + "-"*70)
            print("BY TICKER:")
            for ticker, data in sorted(stats['by_ticker'].items(),
                                      key=lambda x: x[1]['pnl'], reverse=True):
                total = data['wins'] + data['losses']
                wr = (data['wins'] / total * 100) if total > 0 else 0
                print(f"  {ticker:6} | W/L: {data['wins']}/{data['losses']} "
                      f"({wr:.0f}%) | P&L: ${data['pnl']:+.2f}")

        if stats['by_direction']:
            print("\n" + "-"*70)
            print("BY DIRECTION:")
            for direction, data in stats['by_direction'].items():
                total = data['wins'] + data['losses']
                wr = (data['wins'] / total * 100) if total > 0 else 0
                print(f"  {direction:6} | W/L: {data['wins']}/{data['losses']} "
                      f"({wr:.0f}%) | P&L: ${data['pnl']:+.2f}")

        print("="*70 + "\n")


# Global singleton
analytics = SignalAnalytics()


def log_signal(ticker: str, direction: str, entry: float, stop: float,
               target: float, confidence: int, **kwargs) -> int:
    """Convenience function to log a signal."""
    return analytics.log_signal(
        ticker, direction, entry, stop, target, confidence, **kwargs
    )


def update_signal_outcome(signal_id: int, outcome: str,
                         exit_price: float, exit_time=None):
    """Convenience function to update signal outcome."""
    analytics.update_signal_outcome(signal_id, outcome, exit_price, exit_time)


def get_performance_stats(days: int = 30) -> Dict:
    """Convenience function to get performance stats."""
    return analytics.get_performance_stats(days)


def print_performance_report(days: int = 30):
    """Convenience function to print performance report."""
    analytics.print_performance_report(days)
