"""
Signal Analytics Module
Tracks all signals generated by the scanner and monitors their outcomes.

Features:
  - Logs every signal with entry, stop, target details
  - Tracks signal outcomes (hit target, hit stop, expired)
  - Calculates win rate, profit factor, average R:R
  - Generates performance reports for tuning
  - Stores in PostgreSQL for historical analysis
  - Phase 1.10: Advanced performance metrics, quality scoring, optimization recommendations

Usage:
  from signal_analytics import log_signal, update_signal_outcome, get_performance_stats
  
  # When signal fires
  log_signal(ticker, direction, entry, stop, target, confidence, ...)
  
  # When outcome is known (target hit, stop hit, or time expired)
  update_signal_outcome(signal_id, outcome, exit_price, exit_time)
  
  # Get performance stats
  stats = get_performance_stats(days=30)
"""

from datetime import datetime, timedelta, time
from zoneinfo import ZoneInfo
from typing import Dict, List, Optional, Tuple
import db_connection
from db_connection import get_conn, ph, dict_cursor, serial_pk
import statistics
import math

ET = ZoneInfo("America/New_York")


class SignalAnalytics:
    def __init__(self, db_path: str = "market_memory.db"):
        self.db_path = db_path
        self._initialize_tables()

    def _initialize_tables(self):
        """Create signal tracking tables."""
        conn = get_conn(self.db_path)
        cursor = conn.cursor()

        # Main signals table
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS signals (
                id              {serial_pk()},
                ticker          TEXT NOT NULL,
                direction       TEXT NOT NULL,
                signal_time     TIMESTAMP NOT NULL,
                entry_price     REAL NOT NULL,
                stop_price      REAL NOT NULL,
                target_price    REAL NOT NULL,
                risk            REAL NOT NULL,
                reward          REAL NOT NULL,
                risk_reward     REAL NOT NULL,
                confidence      INTEGER NOT NULL,
                volume_multiple REAL,
                atr             REAL,
                signal_type     TEXT,
                
                -- Outcome tracking
                outcome         TEXT,
                exit_price      REAL,
                exit_time       TIMESTAMP,
                pnl             REAL,
                pnl_r           REAL,
                hold_duration   INTEGER,
                
                -- Metadata
                notes           TEXT,
                created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # Migration: Add outcome columns if they don't exist (for existing tables)
        if db_connection.USE_POSTGRES:
            try:
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS outcome TEXT")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS exit_price REAL")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS exit_time TIMESTAMP")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS pnl REAL")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS pnl_r REAL")
                cursor.execute("ALTER TABLE signals ADD COLUMN IF NOT EXISTS hold_duration INTEGER")
                conn.commit()
            except Exception as e:
                # Columns already exist or other error - continue
                conn.rollback()

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_ticker_time
            ON signals(ticker, signal_time DESC)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_outcome
            ON signals(outcome)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_signals_time
            ON signals(signal_time DESC)
        """)

        conn.commit()
        conn.close()
        print("[ANALYTICS] Signal tracking tables initialized")

    def log_signal(self,
                   ticker: str,
                   direction: str,
                   entry: float,
                   stop: float,
                   target: float,
                   confidence: int,
                   volume_multiple: Optional[float] = None,
                   atr: Optional[float] = None,
                   signal_type: Optional[str] = None,
                   notes: Optional[str] = None) -> int:
        """
        Log a new signal to the database.
        Returns the signal ID for later outcome tracking.
        """
        now_et = datetime.now(ET).replace(tzinfo=None)
        risk = abs(entry - stop)
        reward = abs(target - entry)
        risk_reward = reward / risk if risk > 0 else 0

        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)

        if db_connection.USE_POSTGRES:
            sql = f"""
                INSERT INTO signals (
                    ticker, direction, signal_time, entry_price, stop_price,
                    target_price, risk, reward, risk_reward, confidence,
                    volume_multiple, atr, signal_type, notes
                ) VALUES (
                    {p}, {p}, {p}, {p}, {p},
                    {p}, {p}, {p}, {p}, {p},
                    {p}, {p}, {p}, {p}
                ) RETURNING id
            """
        else:
            sql = f"""
                INSERT INTO signals (
                    ticker, direction, signal_time, entry_price, stop_price,
                    target_price, risk, reward, risk_reward, confidence,
                    volume_multiple, atr, signal_type, notes
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """

        cursor.execute(sql, (
            ticker, direction, now_et, entry, stop,
            target, risk, reward, risk_reward, confidence,
            volume_multiple, atr, signal_type, notes
        ))

        if db_connection.USE_POSTGRES:
            signal_id = cursor.fetchone()["id"]
        else:
            signal_id = cursor.lastrowid

        conn.commit()
        conn.close()

        print(f"[ANALYTICS] 📊 Logged signal #{signal_id}: {ticker} {direction} @ ${entry:.2f}")
        return signal_id

    def update_signal_outcome(self,
                            signal_id: int,
                            outcome: str,
                            exit_price: float,
                            exit_time: Optional[datetime] = None) -> None:
        """
        Update signal outcome when target/stop is hit or signal expires.
        
        Args:
            signal_id: ID from log_signal()
            outcome: 'WIN' | 'LOSS' | 'BREAKEVEN' | 'EXPIRED'
            exit_price: Actual exit price
            exit_time: Exit timestamp (defaults to now)
        """
        if exit_time is None:
            exit_time = datetime.now(ET).replace(tzinfo=None)

        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)

        # Get original signal data
        cursor.execute(f"""
            SELECT entry_price, stop_price, target_price, direction, signal_time, risk
            FROM signals WHERE id = {p}
        """, (signal_id,))
        row = cursor.fetchone()
        if not row:
            print(f"[ANALYTICS] ⚠️ Signal #{signal_id} not found")
            conn.close()
            return

        entry = row["entry_price"]
        direction = row["direction"]
        signal_time = row["signal_time"]
        risk = row["risk"]

        # Calculate P&L
        if direction.lower() in ["bull", "long", "buy"]:
            pnl = exit_price - entry
        else:
            pnl = entry - exit_price

        pnl_r = pnl / risk if risk > 0 else 0

        # Calculate hold duration in minutes
        if isinstance(signal_time, str):
            signal_time = datetime.fromisoformat(signal_time)
        hold_duration = int((exit_time - signal_time).total_seconds() / 60)

        # Update record
        cursor.execute(f"""
            UPDATE signals
            SET outcome = {p}, exit_price = {p}, exit_time = {p},
                pnl = {p}, pnl_r = {p}, hold_duration = {p}
            WHERE id = {p}
        """, (outcome, exit_price, exit_time, pnl, pnl_r, hold_duration, signal_id))

        conn.commit()
        conn.close()

        print(f"[ANALYTICS] ✅ Signal #{signal_id} outcome: {outcome} | "
              f"P&L: ${pnl:+.2f} ({pnl_r:+.2f}R) | Hold: {hold_duration}m")

    def get_performance_stats(self, days: int = 30) -> Dict:
        """
        Calculate performance statistics for completed signals.
        
        Returns comprehensive performance metrics including Phase 1.10 enhancements.
        """
        cutoff = datetime.now(ET) - timedelta(days=days)
        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)

        # All signals in period
        cursor.execute(f"""
            SELECT COUNT(*) as cnt FROM signals
            WHERE signal_time >= {p}
        """, (cutoff,))
        total_signals = cursor.fetchone()["cnt"]

        # Completed signals only
        cursor.execute(f"""
            SELECT ticker, direction, outcome, pnl, pnl_r, hold_duration, risk_reward,
                   confidence, signal_time, signal_type, volume_multiple
            FROM signals
            WHERE signal_time >= {p}
              AND outcome IS NOT NULL
        """, (cutoff,))
        rows = cursor.fetchall()
        conn.close()

        if not rows:
            return self._empty_stats(total_signals)

        # Basic metrics
        completed = len(rows)
        wins = [r for r in rows if r["outcome"] == "WIN"]
        losses = [r for r in rows if r["outcome"] == "LOSS"]
        win_count = len(wins)
        loss_count = len(losses)
        win_rate = (win_count / completed * 100) if completed > 0 else 0.0

        avg_win = sum(r["pnl"] for r in wins) / win_count if win_count > 0 else 0.0
        avg_loss = sum(r["pnl"] for r in losses) / loss_count if loss_count > 0 else 0.0

        total_wins_pnl = sum(r["pnl"] for r in wins)
        total_losses_pnl = abs(sum(r["pnl"] for r in losses))
        profit_factor = (total_wins_pnl / total_losses_pnl) if total_losses_pnl > 0 else 0.0

        avg_rr = sum(r["risk_reward"] for r in rows) / completed
        avg_hold = sum(r["hold_duration"] or 0 for r in rows) / completed
        total_pnl = sum(r["pnl"] or 0 for r in rows)
        total_r = sum(r["pnl_r"] or 0 for r in rows)

        # Phase 1.10: Advanced metrics
        expectancy = self._calculate_expectancy(rows)
        sharpe = self._calculate_sharpe_ratio(rows)
        max_dd = self._calculate_max_drawdown(rows)
        quality_score = self._calculate_quality_score(win_rate, profit_factor, avg_rr)
        confidence_calibration = self._analyze_confidence_calibration(rows)
        time_of_day_stats = self._analyze_time_of_day(rows)
        signal_type_stats = self._analyze_by_signal_type(rows)

        # By ticker/direction (existing logic)
        by_ticker = self._group_by_ticker(rows)
        by_direction = self._group_by_direction(rows)

        return {
            'total_signals': total_signals,
            'completed': completed,
            'wins': win_count,
            'losses': loss_count,
            'win_rate': win_rate,
            'avg_win': avg_win,
            'avg_loss': avg_loss,
            'profit_factor': profit_factor,
            'avg_rr': avg_rr,
            'avg_hold_mins': avg_hold,
            'total_pnl': total_pnl,
            'total_r': total_r,
            'by_ticker': by_ticker,
            'by_direction': by_direction,
            # Phase 1.10: Advanced metrics
            'expectancy': expectancy,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'quality_score': quality_score,
            'confidence_calibration': confidence_calibration,
            'time_of_day': time_of_day_stats,
            'by_signal_type': signal_type_stats
        }

    def _empty_stats(self, total_signals: int) -> Dict:
        """Return empty stats dict."""
        return {
            'total_signals': total_signals,
            'completed': 0,
            'wins': 0,
            'losses': 0,
            'win_rate': 0.0,
            'avg_win': 0.0,
            'avg_loss': 0.0,
            'profit_factor': 0.0,
            'avg_rr': 0.0,
            'avg_hold_mins': 0.0,
            'total_pnl': 0.0,
            'total_r': 0.0,
            'by_ticker': {},
            'by_direction': {},
            'expectancy': 0.0,
            'sharpe_ratio': 0.0,
            'max_drawdown': 0.0,
            'quality_score': 0.0,
            'confidence_calibration': {},
            'time_of_day': {},
            'by_signal_type': {}
        }

    def _calculate_expectancy(self, rows: List[Dict]) -> float:
        """
        Phase 1.10: Calculate expectancy (average $ per trade).
        Expectancy = (Win% × Avg Win) - (Loss% × Avg Loss)
        """
        if not rows:
            return 0.0
        
        wins = [r for r in rows if r["outcome"] == "WIN"]
        losses = [r for r in rows if r["outcome"] == "LOSS"]
        
        win_rate = len(wins) / len(rows)
        loss_rate = len(losses) / len(rows)
        
        avg_win = sum(r["pnl"] for r in wins) / len(wins) if wins else 0.0
        avg_loss = abs(sum(r["pnl"] for r in losses) / len(losses)) if losses else 0.0
        
        return (win_rate * avg_win) - (loss_rate * avg_loss)

    def _calculate_sharpe_ratio(self, rows: List[Dict]) -> float:
        """
        Phase 1.10: Calculate Sharpe ratio (risk-adjusted returns).
        Sharpe = (Mean Return) / (Std Dev of Returns)
        """
        if len(rows) < 2:
            return 0.0
        
        returns = [r["pnl_r"] or 0 for r in rows]
        mean_return = statistics.mean(returns)
        std_dev = statistics.stdev(returns)
        
        if std_dev == 0:
            return 0.0
        
        # Annualized Sharpe (assuming ~250 trading days, ~6 trades/day)
        return (mean_return / std_dev) * math.sqrt(250 * 6)

    def _calculate_max_drawdown(self, rows: List[Dict]) -> float:
        """
        Phase 1.10: Calculate maximum drawdown percentage.
        """
        if not rows:
            return 0.0
        
        # Sort by time
        sorted_rows = sorted(rows, key=lambda r: r["signal_time"])
        
        cumulative_pnl = 0.0
        peak = 0.0
        max_dd = 0.0
        
        for row in sorted_rows:
            cumulative_pnl += (row["pnl"] or 0)
            if cumulative_pnl > peak:
                peak = cumulative_pnl
            
            drawdown = ((cumulative_pnl - peak) / peak * 100) if peak > 0 else 0.0
            max_dd = min(max_dd, drawdown)
        
        return abs(max_dd)

    def _calculate_quality_score(self, win_rate: float, profit_factor: float, avg_rr: float) -> float:
        """
        Phase 1.10: Calculate overall signal quality score (0-100).
        
        Factors:
        - Win rate (target 60%+)
        - Profit factor (target 2.0+)
        - Avg R:R (target 2.0+)
        """
        wr_score = min(win_rate / 60.0 * 40, 40)  # Max 40 pts
        pf_score = min(profit_factor / 2.0 * 35, 35)  # Max 35 pts
        rr_score = min(avg_rr / 2.0 * 25, 25)  # Max 25 pts
        
        return round(wr_score + pf_score + rr_score, 1)

    def _analyze_confidence_calibration(self, rows: List[Dict]) -> Dict:
        """
        Phase 1.10: Analyze if confidence scores match actual win rates.
        
        Returns dict with confidence buckets and their actual win rates.
        """
        buckets = {
            '90-100%': {'total': 0, 'wins': 0, 'actual_wr': 0.0},
            '80-89%': {'total': 0, 'wins': 0, 'actual_wr': 0.0},
            '70-79%': {'total': 0, 'wins': 0, 'actual_wr': 0.0},
            '60-69%': {'total': 0, 'wins': 0, 'actual_wr': 0.0},
            '<60%': {'total': 0, 'wins': 0, 'actual_wr': 0.0}
        }
        
        for row in rows:
            conf = row["confidence"]
            is_win = row["outcome"] == "WIN"
            
            if conf >= 90:
                bucket = '90-100%'
            elif conf >= 80:
                bucket = '80-89%'
            elif conf >= 70:
                bucket = '70-79%'
            elif conf >= 60:
                bucket = '60-69%'
            else:
                bucket = '<60%'
            
            buckets[bucket]['total'] += 1
            if is_win:
                buckets[bucket]['wins'] += 1
        
        # Calculate actual win rates
        for bucket, data in buckets.items():
            if data['total'] > 0:
                data['actual_wr'] = (data['wins'] / data['total']) * 100
        
        return buckets

    def _analyze_time_of_day(self, rows: List[Dict]) -> Dict:
        """
        Phase 1.10: Analyze performance by time of day.
        """
        periods = {
            'Opening (9:30-10:00)': {'wins': 0, 'losses': 0, 'pnl': 0.0},
            'Morning (10:00-12:00)': {'wins': 0, 'losses': 0, 'pnl': 0.0},
            'Midday (12:00-14:00)': {'wins': 0, 'losses': 0, 'pnl': 0.0},
            'Afternoon (14:00-16:00)': {'wins': 0, 'losses': 0, 'pnl': 0.0}
        }
        
        for row in rows:
            signal_time = row["signal_time"]
            if isinstance(signal_time, str):
                signal_time = datetime.fromisoformat(signal_time)
            
            hour = signal_time.hour
            minute = signal_time.minute
            
            if hour == 9 and minute >= 30:
                period = 'Opening (9:30-10:00)'
            elif 10 <= hour < 12:
                period = 'Morning (10:00-12:00)'
            elif 12 <= hour < 14:
                period = 'Midday (12:00-14:00)'
            elif 14 <= hour < 16:
                period = 'Afternoon (14:00-16:00)'
            else:
                continue
            
            if row["outcome"] == "WIN":
                periods[period]['wins'] += 1
            elif row["outcome"] == "LOSS":
                periods[period]['losses'] += 1
            periods[period]['pnl'] += (row["pnl"] or 0)
        
        return periods

    def _analyze_by_signal_type(self, rows: List[Dict]) -> Dict:
        """
        Phase 1.10: Analyze performance by signal type (BREAKOUT, RETEST, etc.).
        """
        by_type = {}
        for row in rows:
            sig_type = row.get("signal_type") or "UNKNOWN"
            if sig_type not in by_type:
                by_type[sig_type] = {'wins': 0, 'losses': 0, 'pnl': 0.0}
            
            if row["outcome"] == "WIN":
                by_type[sig_type]['wins'] += 1
            elif row["outcome"] == "LOSS":
                by_type[sig_type]['losses'] += 1
            by_type[sig_type]['pnl'] += (row["pnl"] or 0)
        
        return by_type

    def _group_by_ticker(self, rows: List[Dict]) -> Dict:
        """Group signals by ticker."""
        by_ticker = {}
        for row in rows:
            t = row["ticker"]
            if t not in by_ticker:
                by_ticker[t] = {'wins': 0, 'losses': 0, 'pnl': 0.0}
            if row["outcome"] == "WIN":
                by_ticker[t]['wins'] += 1
            elif row["outcome"] == "LOSS":
                by_ticker[t]['losses'] += 1
            by_ticker[t]['pnl'] += (row["pnl"] or 0)
        return by_ticker

    def _group_by_direction(self, rows: List[Dict]) -> Dict:
        """Group signals by direction."""
        by_direction = {}
        for row in rows:
            d = row["direction"]
            if d not in by_direction:
                by_direction[d] = {'wins': 0, 'losses': 0, 'pnl': 0.0}
            if row["outcome"] == "WIN":
                by_direction[d]['wins'] += 1
            elif row["outcome"] == "LOSS":
                by_direction[d]['losses'] += 1
            by_direction[d]['pnl'] += (row["pnl"] or 0)
        return by_direction

    def get_optimization_recommendations(self, days: int = 30) -> List[str]:
        """
        Phase 1.10: Generate automated optimization recommendations based on performance data.
        
        Returns list of actionable recommendations.
        """
        stats = self.get_performance_stats(days)
        recommendations = []
        
        # Win rate analysis
        if stats['win_rate'] < 50:
            recommendations.append("⚠️ Win rate below 50% - Consider increasing confidence threshold")
        elif stats['win_rate'] > 70:
            recommendations.append("✅ Excellent win rate - System is performing well")
        
        # Profit factor analysis
        if stats['profit_factor'] < 1.5:
            recommendations.append("⚠️ Low profit factor - Review stop loss placement and target levels")
        elif stats['profit_factor'] > 2.5:
            recommendations.append("✅ Strong profit factor - Risk/reward management is excellent")
        
        # Confidence calibration
        for bucket, data in stats['confidence_calibration'].items():
            if data['total'] >= 10:  # Enough sample size
                expected_wr = int(bucket.split('-')[0].replace('%', '').replace('<', '0'))
                actual_wr = data['actual_wr']
                deviation = abs(actual_wr - expected_wr)
                
                if deviation > 15:
                    recommendations.append(
                        f"⚠️ Confidence {bucket} signals have {actual_wr:.0f}% win rate "
                        f"(expected ~{expected_wr}%) - Recalibrate confidence scoring"
                    )
        
        # Time of day performance
        best_period = max(stats['time_of_day'].items(), 
                         key=lambda x: x[1]['pnl'] if x[1]['pnl'] else -999)
        worst_period = min(stats['time_of_day'].items(),
                          key=lambda x: x[1]['pnl'] if x[1]['pnl'] else 999)
        
        if best_period[1]['pnl'] > 0 and worst_period[1]['pnl'] < 0:
            recommendations.append(
                f"📈 Best performance: {best_period[0]} (${best_period[1]['pnl']:+.0f})"
            )
            recommendations.append(
                f"📉 Worst performance: {worst_period[0]} (${worst_period[1]['pnl']:+.0f}) "
                "- Consider avoiding this period"
            )
        
        # Sharpe ratio analysis
        if stats['sharpe_ratio'] < 1.0:
            recommendations.append("⚠️ Low Sharpe ratio - Returns not justifying risk taken")
        elif stats['sharpe_ratio'] > 2.0:
            recommendations.append("✅ Excellent Sharpe ratio - Strong risk-adjusted returns")
        
        # Max drawdown
        if stats['max_drawdown'] > 15:
            recommendations.append(
                f"⚠️ High max drawdown ({stats['max_drawdown']:.1f}%) - "
                "Implement stricter position sizing or daily loss limits"
            )
        
        # Quality score
        quality = stats['quality_score']
        if quality < 60:
            recommendations.append(f"⚠️ Quality score {quality:.0f}/100 - System needs optimization")
        elif quality > 80:
            recommendations.append(f"✅ Quality score {quality:.0f}/100 - Excellent signal quality")
        
        if not recommendations:
            recommendations.append("ℹ️ Insufficient data for recommendations (need 30+ completed signals)")
        
        return recommendations

    def get_recent_signals(self, limit: int = 50, hours: Optional[int] = None) -> List[Dict]:
        """
        Get most recent signals with outcomes.
        
        Args:
            limit: Maximum number of signals to return
            hours: Optional filter for signals within last N hours
        """
        p = ph()
        conn = get_conn(self.db_path)
        cursor = dict_cursor(conn)
        
        if hours:
            cutoff = datetime.now(ET) - timedelta(hours=hours)
            cursor.execute(f"""
                SELECT id, ticker, direction, signal_time, entry_price, stop_price,
                       target_price, risk, reward, risk_reward, confidence,
                       outcome, exit_price, exit_time, pnl, pnl_r, hold_duration
                FROM signals
                WHERE signal_time >= {p}
                ORDER BY signal_time DESC
                LIMIT {p}
            """, (cutoff, limit))
        else:
            cursor.execute(f"""
                SELECT id, ticker, direction, signal_time, entry_price, stop_price,
                       target_price, risk, reward, risk_reward, confidence,
                       outcome, exit_price, exit_time, pnl, pnl_r, hold_duration
                FROM signals
                ORDER BY signal_time DESC
                LIMIT {p}
            """, (limit,))
        
        rows = cursor.fetchall()
        conn.close()
        return [dict(row) for row in rows]

    def print_performance_report(self, days: int = 30):
        """
        Print formatted performance report.
        
        Phase 1.10: Enhanced with advanced metrics and recommendations.
        """
        stats = self.get_performance_stats(days)

        print("\n" + "="*70)
        print(f"SIGNAL PERFORMANCE REPORT - Last {days} Days")
        print("="*70)
        print(f"Total Signals:    {stats['total_signals']}")
        print(f"Completed:        {stats['completed']}")
        print(f"Wins:             {stats['wins']}")
        print(f"Losses:           {stats['losses']}")
        print(f"Win Rate:         {stats['win_rate']:.1f}%")
        print(f"Avg Win:          ${stats['avg_win']:.2f}")
        print(f"Avg Loss:         ${stats['avg_loss']:.2f}")
        print(f"Profit Factor:    {stats['profit_factor']:.2f}")
        print(f"Avg R:R:          {stats['avg_rr']:.2f}")
        print(f"Avg Hold:         {stats['avg_hold_mins']:.0f} mins")
        print(f"Total P&L:        ${stats['total_pnl']:+.2f}")
        print(f"Total R:          {stats['total_r']:+.2f}R")
        
        # Phase 1.10: Advanced metrics
        print("\n" + "-"*70)
        print("ADVANCED METRICS:")
        print(f"Expectancy:       ${stats['expectancy']:+.2f} per trade")
        print(f"Sharpe Ratio:     {stats['sharpe_ratio']:.2f}")
        print(f"Max Drawdown:     {stats['max_drawdown']:.1f}%")
        print(f"Quality Score:    {stats['quality_score']:.0f}/100")

        if stats['by_ticker']:
            print("\n" + "-"*70)
            print("BY TICKER:")
            for ticker, data in sorted(stats['by_ticker'].items(),
                                      key=lambda x: x[1]['pnl'], reverse=True)[:10]:
                total = data['wins'] + data['losses']
                wr = (data['wins'] / total * 100) if total > 0 else 0
                print(f"  {ticker:6} | W/L: {data['wins']}/{data['losses']} "
                      f"({wr:.0f}%) | P&L: ${data['pnl']:+.2f}")

        if stats['by_direction']:
            print("\n" + "-"*70)
            print("BY DIRECTION:")
            for direction, data in stats['by_direction'].items():
                total = data['wins'] + data['losses']
                wr = (data['wins'] / total * 100) if total > 0 else 0
                print(f"  {direction:6} | W/L: {data['wins']}/{data['losses']} "
                      f"({wr:.0f}%) | P&L: ${data['pnl']:+.2f}")
        
        # Phase 1.10: Time of day performance
        if any(v['wins'] + v['losses'] > 0 for v in stats['time_of_day'].values()):
            print("\n" + "-"*70)
            print("BY TIME OF DAY:")
            for period, data in stats['time_of_day'].items():
                total = data['wins'] + data['losses']
                if total > 0:
                    wr = (data['wins'] / total * 100)
                    print(f"  {period:25} | W/L: {data['wins']}/{data['losses']} "
                          f"({wr:.0f}%) | P&L: ${data['pnl']:+.2f}")
        
        # Phase 1.10: Optimization recommendations
        print("\n" + "="*70)
        print("OPTIMIZATION RECOMMENDATIONS:")
        print("="*70)
        recommendations = self.get_optimization_recommendations(days)
        for rec in recommendations:
            print(f"  {rec}")

        print("="*70 + "\n")


# Global singleton
analytics = SignalAnalytics()


def log_signal(ticker: str, direction: str, entry: float, stop: float,
               target: float, confidence: int, **kwargs) -> int:
    """Convenience function to log a signal."""
    return analytics.log_signal(
        ticker, direction, entry, stop, target, confidence, **kwargs
    )


def update_signal_outcome(signal_id: int, outcome: str,
                         exit_price: float, exit_time=None):
    """Convenience function to update signal outcome."""
    analytics.update_signal_outcome(signal_id, outcome, exit_price, exit_time)


def get_performance_stats(days: int = 30) -> Dict:
    """Convenience function to get performance stats."""
    return analytics.get_performance_stats(days)


def get_recent_signals(hours: Optional[int] = None, limit: int = 50) -> List[Dict]:
    """Convenience function to get recent signals."""
    return analytics.get_recent_signals(limit=limit, hours=hours)


def print_performance_report(days: int = 30):
    """Convenience function to print performance report."""
    analytics.print_performance_report(days)


def get_optimization_recommendations(days: int = 30) -> List[str]:
    """Convenience function to get optimization recommendations."""
    return analytics.get_optimization_recommendations(days)
